### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by AlexBrunetti** [aherbrich/Poppy.jl#5]
Since Julia is not very common, could you please provide a Windows executable of your engine?

Thanks,
Alex

**Comment by aherbrich** [comment]
Hi Alex,

Thank you for your interest in my chess engine and for taking the time to reach out!

At this stage, my engine is still under heavy development and experimentation. I somewhat blindly misused the release feature to catalog my evaluation function model, which I’m still experimenting with independently of its actual use in the search algorithm and engine. As such, it's not in a state where providing an executable would be of much value.

However, I'm glad to see there is interest, and I plan to work towards a more stable release in the future.

In the meantime, I will update the README and repository description to better reflect the current status of the project and set appropriate expectations. I'll close this issue for now, but feel free to reopen it at a later time:)
